# Generated by Django 4.2 on 2023-04-10 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0005_rename_description_note_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question', models.CharField(max_length=100, verbose_name='Question')),
                ('answer', models.CharField(max_length=100, verbose_name='Answer')),
                ('case_strict', models.BooleanField(default=True, verbose_name='is case strict')),
                ('diacritic_strict', models.BooleanField(default=True, verbose_name='is diacritic strict')),
                ('symbol_strict', models.BooleanField(default=True, verbose_name='is symbol strict')),
                ('can_be_mashed', models.BooleanField(default=True, verbose_name='the result is in different order')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('subject_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='chapter_id')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='index.note')),
            ],
        ),
    ]
