# Generated by Django 4.2 on 2023-04-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='title',
        ),
    ]
