# Generated by Django 4.2 on 2023-04-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_book_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='test',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
